# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./WebAPI/WebAPI.csproj
    - name: Build 
      run: dotnet build ./WebAPI/WebAPI.csproj --no-restore
    - name: Sonar Scanner
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: >
          -Dsonar.login=efa91e67eb480d39584b6ac22e49dbd3ca2ce04d
          -Dsonar.projectKey=mayankprajapati1011_AspDotNetCoreWebAPI
          -Dsonar.organization=mayankprajapati1011
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.projectBaseDir=.
    
